#!/usr/bin/env php
<?php
/**
 * Flickr to WordPress XML Exporter
 * 
 * Converts Flickr JSON data to WordPress WXR XML format
 * for import via WordPress Admin → Tools → Import → WordPress
 * 
 * Requirements: PHP 8.3+
 * Usage: php flickr-to-wordpress-xml.php --json-dir=path --output=file.xml
 */

declare(strict_types=1);

class FlickrToWordPressXMLExporter
{
    private array $options = [];
    private int $postIdCounter = 1;
    private int $termIdCounter = 1;
    private array $albumTagMap = [];
    private $xmlFile;
    
    public function __construct(array $options)
    {
        $this->options = array_merge([
            'site-url' => 'https://example.com',
            'author' => 'admin',
            'dry-run' => false,
            'verbose' => false
        ], $options);
        
        $this->validateOptions();
    }
    
    private function validateOptions(): void
    {
        if (!isset($this->options['json-dir']) || !is_dir($this->options['json-dir'])) {
            throw new InvalidArgumentException('--json-dir must be a valid directory');
        }
        
        if (!isset($this->options['output'])) {
            throw new InvalidArgumentException('--output is required');
        }
        
        if (!$this->options['dry-run'] && !is_writable(dirname($this->options['output']))) {
            throw new InvalidArgumentException('Output directory must be writable');
        }
    }
    
    public function export(): void
    {
        $this->log("Starting Flickr to WordPress XML export...");
        
        $albumsData = $this->loadAlbumsData();
        $photoFiles = $this->getPhotoFiles();
        
        $this->log(sprintf("Found %d albums and %d photo files", count($albumsData['albums']), count($photoFiles)));
        
        if (!$this->options['dry-run']) {
            $this->xmlFile = fopen($this->options['output'], 'w');
            if (!$this->xmlFile) {
                throw new RuntimeException('Could not open output file for writing');
            }
        }
        
        try {
            $this->writeXMLHeader();
            $this->processTags($albumsData['albums']);
            $this->processPhotos($photoFiles, $albumsData['albums']);
            $this->writeXMLFooter();
            
            if (!$this->options['dry-run']) {
                fclose($this->xmlFile);
            }
            
            $this->log("Export completed successfully!");
            $this->printSummary();
            
        } catch (Exception $e) {
            if ($this->xmlFile) {
                fclose($this->xmlFile);
                if (!$this->options['dry-run']) {
                    unlink($this->options['output']);
                }
            }
            throw $e;
        }
    }
    
    private function loadAlbumsData(): array
    {
        $albumsFile = $this->options['json-dir'] . '/albums.json';
        if (!file_exists($albumsFile)) {
            throw new RuntimeException('albums.json not found in JSON directory');
        }
        
        $data = json_decode(file_get_contents($albumsFile), true);
        if (!$data || !isset($data['albums'])) {
            throw new RuntimeException('Invalid albums.json format');
        }
        
        return $data;
    }
    
    private function getPhotoFiles(): array
    {
        $pattern = $this->options['json-dir'] . '/photo_*.json';
        return glob($pattern) ?: [];
    }
    
    private function writeXMLHeader(): void
    {
        $siteUrl = $this->options['site-url'];
        $currentDate = date('r');
        
        $header = <<<XML
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by Flickr to WordPress XML Exporter -->
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
>
<channel>
    <title><![CDATA[Flickr Photo Import]]></title>
    <link>{$siteUrl}</link>
    <description><![CDATA[Imported from Flickr]]></description>
    <pubDate>{$currentDate}</pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url>{$siteUrl}</wp:base_site_url>
    <wp:base_blog_url>{$siteUrl}</wp:base_blog_url>
    
    <wp:author>
        <wp:author_id>1</wp:author_id>
        <wp:author_login><![CDATA[{$this->options['author']}]]></wp:author_login>
        <wp:author_email><![CDATA[{$this->options['author']}@example.com]]></wp:author_email>
        <wp:author_display_name><![CDATA[{$this->options['author']}]]></wp:author_display_name>
    </wp:author>


XML;

        $this->writeXML($header);
    }
    
    private function processTags(array $albums): void
    {
        $this->log("Processing album tags...");
        
        foreach ($albums as $album) {
            $tagId = $this->termIdCounter++;
            $tagName = $album['title'];
            $tagSlug = $this->generateSlug($tagName);
            $tagDescription = $album['description'] ?? '';
            
            $this->albumTagMap[$album['id']] = [
                'id' => $tagId,
                'name' => $tagName,
                'slug' => $tagSlug
            ];
            
            $tagXML = <<<XML
    <wp:tag>
        <wp:term_id>{$tagId}</wp:term_id>
        <wp:tag_slug><![CDATA[{$tagSlug}]]></wp:tag_slug>
        <wp:tag_name><![CDATA[{$tagName}]]></wp:tag_name>
        <wp:term_description><![CDATA[{$tagDescription}]]></wp:term_description>
    </wp:tag>

XML;
            
            $this->writeXML($tagXML);
            $this->verbose("Created tag: {$tagName} ({$tagSlug})");
        }
        
        // Add the flickr-to-wp tag
        $flickrTagId = $this->termIdCounter++;
        $flickrTagXML = <<<XML
    <wp:tag>
        <wp:term_id>{$flickrTagId}</wp:term_id>
        <wp:tag_slug><![CDATA[flickr-to-wp]]></wp:tag_slug>
        <wp:tag_name><![CDATA[flickr-to-wp]]></wp:tag_name>
        <wp:term_description><![CDATA[Imported from Flickr]]></wp:term_description>
    </wp:tag>

XML;
        
        $this->writeXML($flickrTagXML);
        $this->log(sprintf("Created %d album tags", count($albums)));
    }
    
    private function processPhotos(array $photoFiles, array $albums): void
    {
        $this->log("Processing photos...");
        $processed = 0;
        $skipped = 0;
        
        foreach ($photoFiles as $photoFile) {
            try {
                $photoData = json_decode(file_get_contents($photoFile), true);
                if (!$photoData) {
                    $this->log("ERROR: Corrupted JSON file: " . basename($photoFile));
                    $skipped++;
                    continue;
                }
                
                if (!isset($photoData['original'])) {
                    $this->log("WARNING: Missing original URL in: " . basename($photoFile));
                    $skipped++;
                    continue;
                }
                
                $this->processPhoto($photoData, $albums);
                $processed++;
                
                if ($processed % 50 === 0) {
                    $this->log("Processed {$processed} photos...");
                }
                
            } catch (Exception $e) {
                $this->log("ERROR processing " . basename($photoFile) . ": " . $e->getMessage());
                $skipped++;
            }
        }
        
        $this->log(sprintf("Processed %d photos, skipped %d", $processed, $skipped));
    }
    
    private function processPhoto(array $photo, array $albums): void
    {
        // Generate post data
        $postId = $this->postIdCounter++;
        $attachmentId = $this->postIdCounter++;
        
        $postTitle = $photo['name'] ?: "Photo taken at " . $photo['date_taken'];
        $postSlug = $this->generateSlug($postTitle . '-' . $photo['id']);
        
        $postContent = $this->generatePostContent($photo);
        $postDate = $this->formatDate($photo['date_imported'] ?: $photo['date_taken']);
        $postDateGMT = $this->formatDateGMT($photo['date_imported'] ?: $photo['date_taken']);
        
        $permalink = $this->options['site-url'] . '/' . date('Y/m/d', strtotime($postDate)) . '/' . $postSlug . '/';
        $guid = $this->options['site-url'] . '/?p=' . $postId;
        
        // Write attachment first
        $this->writeAttachment($attachmentId, $photo, $postId, $postDate, $postDateGMT);
        
        // Write post
        $postXML = <<<XML
    <item>
        <title><![CDATA[{$postTitle}]]></title>
        <link>{$permalink}</link>
        <pubDate>{$this->formatRFC2822($postDate)}</pubDate>
        <dc:creator><![CDATA[{$this->options['author']}]]></dc:creator>
        <guid isPermaLink="false">{$guid}</guid>
        <description></description>
        <content:encoded><![CDATA[{$postContent}]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id>{$postId}</wp:post_id>
        <wp:post_date><![CDATA[{$postDate}]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[{$postDateGMT}]]></wp:post_date_gmt>
        <wp:post_modified><![CDATA[{$postDate}]]></wp:post_modified>
        <wp:post_modified_gmt><![CDATA[{$postDateGMT}]]></wp:post_modified_gmt>
        <wp:comment_status><![CDATA[open]]></wp:comment_status>
        <wp:ping_status><![CDATA[open]]></wp:ping_status>
        <wp:post_name><![CDATA[{$postSlug}]]></wp:post_name>
        <wp:status><![CDATA[publish]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[post]]></wp:post_type>
        <wp:post_password><![CDATA[]]></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
        
        <category domain="post_tag" nicename="flickr-to-wp"><![CDATA[flickr-to-wp]]></category>

XML;

        // Add album tags
        foreach ($photo['albums'] as $albumRef) {
            $albumId = is_array($albumRef) ? $albumRef['id'] : $albumRef;
            if (isset($this->albumTagMap[$albumId])) {
                $tag = $this->albumTagMap[$albumId];
                $postXML .= "        <category domain=\"post_tag\" nicename=\"{$tag['slug']}\"><![CDATA[{$tag['name']}]]></category>\n";
            }
        }
        
        // Add featured image meta
        $postXML .= <<<XML
        
        <wp:postmeta>
            <wp:meta_key><![CDATA[_thumbnail_id]]></wp:meta_key>
            <wp:meta_value><![CDATA[{$attachmentId}]]></wp:meta_value>
        </wp:postmeta>
    </item>

XML;

        $this->writeXML($postXML);
        $this->verbose("Created post: {$postTitle}");
    }
    
    private function writeAttachment(int $attachmentId, array $photo, int $parentId, string $postDate, string $postDateGMT): void
    {
        $attachmentSlug = $this->generateSlug($photo['name'] . '-' . $photo['id']);
        $attachmentTitle = $photo['name'] ?: "Photo " . $photo['id'];
        $attachmentUrl = $photo['original'];
        
        $exifData = $this->formatEXIFData($photo['exif'] ?? []);
        
        $attachmentXML = <<<XML
    <item>
        <title><![CDATA[{$attachmentTitle}]]></title>
        <link>{$attachmentUrl}</link>
        <pubDate>{$this->formatRFC2822($postDate)}</pubDate>
        <dc:creator><![CDATA[{$this->options['author']}]]></dc:creator>
        <guid isPermaLink="false">{$attachmentUrl}</guid>
        <description><![CDATA[{$exifData}]]></description>
        <content:encoded><![CDATA[{$exifData}]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id>{$attachmentId}</wp:post_id>
        <wp:post_date><![CDATA[{$postDate}]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[{$postDateGMT}]]></wp:post_date_gmt>
        <wp:post_modified><![CDATA[{$postDate}]]></wp:post_modified>
        <wp:post_modified_gmt><![CDATA[{$postDateGMT}]]></wp:post_modified_gmt>
        <wp:comment_status><![CDATA[open]]></wp:comment_status>
        <wp:ping_status><![CDATA[closed]]></wp:ping_status>
        <wp:post_name><![CDATA[{$attachmentSlug}]]></wp:post_name>
        <wp:status><![CDATA[inherit]]></wp:status>
        <wp:post_parent>{$parentId}</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[attachment]]></wp:post_type>
        <wp:post_password><![CDATA[]]></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
        
        <wp:attachment_url><![CDATA[{$attachmentUrl}]]></wp:attachment_url>
    </item>

XML;

        $this->writeXML($attachmentXML);
    }
    
    private function generatePostContent(array $photo): string
    {
        $content = [];
        
        if (!empty($photo['description'])) {
            $content[] = $photo['description'];
        }
        
        $content[] = "Taken on " . $photo['date_taken'];
        $content[] = "Originally from: " . $photo['photopage'];
        
        return implode("\n\n", $content);
    }
    
    private function formatEXIFData(array $exif): string
    {
        if (empty($exif)) {
            return '';
        }
        
        $lines = ['flickr_exif_data:'];
        foreach ($exif as $key => $value) {
            $lines[] = "• {$key}: {$value}";
        }
        
        return implode("\n", $lines);
    }
    
    private function generateSlug(string $text): string
    {
        $slug = strtolower($text);
        $slug = preg_replace('/[^a-z0-9\s-]/', '', $slug);
        $slug = preg_replace('/[\s-]+/', '-', $slug);
        return trim($slug, '-');
    }
    
    private function formatDate(string $date): string
    {
        return date('Y-m-d H:i:s', strtotime($date));
    }
    
    private function formatDateGMT(string $date): string
    {
        return gmdate('Y-m-d H:i:s', strtotime($date));
    }
    
    private function formatRFC2822(string $date): string
    {
        return date('r', strtotime($date));
    }
    
    private function writeXMLFooter(): void
    {
        $footer = <<<XML
</channel>
</rss>
XML;
        $this->writeXML($footer);
    }
    
    private function writeXML(string $content): void
    {
        if (!$this->options['dry-run']) {
            fwrite($this->xmlFile, $content);
        }
    }
    
    private function log(string $message): void
    {
        echo "[" . date('Y-m-d H:i:s') . "] {$message}\n";
    }
    
    private function verbose(string $message): void
    {
        if ($this->options['verbose']) {
            echo "[VERBOSE] {$message}\n";
        }
    }
    
    private function printSummary(): void
    {
        echo "\n=== Export Summary ===\n";
        echo "Albums processed: " . count($this->albumTagMap) . "\n";
        echo "Posts created: " . ($this->postIdCounter - 1) / 2 . "\n"; // Divide by 2 since we create post + attachment
        echo "Output file: " . $this->options['output'] . "\n";
        
        if ($this->options['dry-run']) {
            echo "DRY RUN: No files were actually created\n";
        } else {
            echo "File size: " . $this->formatBytes(filesize($this->options['output'])) . "\n";
        }
        echo "=====================\n\n";
    }
    
    private function formatBytes(int $bytes): string
    {
        $units = ['B', 'KB', 'MB', 'GB'];
        $bytes = max($bytes, 0);
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
        $pow = min($pow, count($units) - 1);
        
        $bytes /= pow(1024, $pow);
        
        return round($bytes, 2) . ' ' . $units[$pow];
    }
}

// Command line interface
function parseArguments(): array
{
    $options = [];
    $args = array_slice($GLOBALS['argv'], 1);
    
    foreach ($args as $arg) {
        if (strpos($arg, '--') === 0) {
            $parts = explode('=', substr($arg, 2), 2);
            $key = $parts[0];
            $value = $parts[1] ?? true;
            
            // Handle boolean flags
            if ($value === 'true') $value = true;
            if ($value === 'false') $value = false;
            
            $options[$key] = $value;
        }
    }
    
    return $options;
}

function showHelp(): void
{
    echo <<<HELP
Flickr to WordPress XML Exporter

Usage: php flickr-to-wordpress-xml.php [OPTIONS]

Required Options:
  --json-dir=PATH      Path to Flickr JSON files directory
  --output=FILE        Output XML file path

Optional Options:
  --site-url=URL       Base URL for permalinks (default: https://example.com)
  --author=USER        WordPress author username (default: admin)
  --dry-run           Generate XML without writing file, show statistics
  --verbose           Show detailed processing information
  --help              Show this help message

Examples:
  php flickr-to-wordpress-xml.php --json-dir=./flickr-data/json --output=./flickr-import.xml
  php flickr-to-wordpress-xml.php --json-dir=./flickr-data/json --output=./flickr-import.xml --site-url=https://mysite.com --verbose
  php flickr-to-wordpress-xml.php --json-dir=./flickr-data/json --output=./test.xml --dry-run

HELP;
}

// Main execution
try {
    $options = parseArguments();
    
    if (isset($options['help']) || empty($options)) {
        showHelp();
        exit(0);
    }
    
    if (!isset($options['json-dir']) || !isset($options['output'])) {
        echo "ERROR: --json-dir and --output are required\n\n";
        showHelp();
        exit(1);
    }
    
    $exporter = new FlickrToWordPressXMLExporter($options);
    $exporter->export();
    
} catch (Exception $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
    exit(1);
}